### ISSUE TITLE
[PluginSubmission]: DWC Can Manager

### ISSUE THREAD

**Issue by Sindarius** [Duet3D/PluginRepository#300]
### Summary

Provides an easy to use list of CAN connected devices.

### GitHub username

Sindarius

### GitHub repository name/Plugin ID

https://github.com/Sindarius/DWC-CAN-Manager

### GitHub branch name

main

**Comment by yasasw** [comment]
Hi @Sindarius 

For GitHub repository name/Plugin ID, you need to submit it as DWC-CAN-Manager
