### ISSUE TITLE
Submission error in process

### ISSUE THREAD

**Issue by MintyTrebor** [Duet3D/PluginRepository#329]
When adding a new submission you receive 2 msgs/emails.
The first reports an error : "Run Failed: remove-plugin - master (7f4b230)"
The second is a breakdown of the plugin submission with each step's completion status.

I am assuming the first msg is in error when submitting a new plugin, as there is nothing to remove.

**Comment by MintyTrebor** [comment]
I now have received Run Failed emails - even though the submission was successful

**Comment by yasasw** [comment]
Hi @MintyTrebor 
Congratulations on submitting your plugins. They are now listed in https://plugins.duet3d.com/

I see. Let me take a look. Can you tell me the issue number?

**Comment by MintyTrebor** [comment]
I received a failure msg for both submissions:
[Duet3D/PluginRepository] Run failed: submit-new-plugin - master (0d1f4dc)
![image](https://user-images.githubusercontent.com/26109080/185400339-18d58eb3-d745-4ed4-8a7f-7e1c106a27a6.png)
[Duet3D/PluginRepository] Run failed: remove-plugin - master (0d1f4dc)
![image](https://user-images.githubusercontent.com/26109080/185400406-21e39a6c-39da-4c14-9f80-f28b8e74b7db.png)

**Comment by MintyTrebor** [comment]
Issues 325 & 327

**Comment by MintyTrebor** [comment]
Also if the README.md file contains images from the plugins repo, they do not display:
![image](https://user-images.githubusercontent.com/26109080/185407023-bfd367e2-7d6c-4bc0-add6-12ca8c7bfc2d.png)

I think this is because its using a url path that is only reachable when using the github website. I have updated BtnCmd README.md to use the following format:

https://raw.githubusercontent.com/<username>/<repo name>/<branch>/<path>/<img name>
eg
https://raw.githubusercontent.com/MintyTrebor/BtnCmd/main/wikires/v0.8.13_BtnCmd_MainWindow_1.png

If its possible to re-pull the README.md to update https://plugins.duet3d.com/plugins/BtnCmd.html we can test if the changes I made works. If it does - it might be worth while adding a section to the submission guide, which describes how to avoid the problem.

**Comment by yasasw** [comment]
Hi @MintyTrebor 
The errors were thrown as the current workflows(both submission/removal) are being triggered for opened issues (and workflow for removal will be force-stopped if the issue was opened for a plugin submission).

**Comment by yasasw** [comment]
Hi @MintyTrebor 
We are still working on the content-updating workflows. Atm, need to remove and resubmit the plugin.
Also, thanks for raising this. I will update the documentation mentioning that the links in README.md should be updated.


I have removed the plugin.
Can you lodge a new submission for BtnCmd?

**Comment by yasasw** [comment]
Thanks and cheers!

**Comment by MintyTrebor** [comment]
Confirmed! the URL structure I posted above does work, and images display properly

**Comment by yasasw** [comment]
Thanks for confirming @MintyTrebor
