### ISSUE TITLE
[PluginUpdate]: 

### ISSUE THREAD

**Issue by Sindarius** [Duet3D/PluginRepository#609]
### Summary

Update for 3.5

### Plugin ID

ObjectCancelPlugin

### Terms and Conditions

- [X] I confirm that this plugin contains no malicious code and/nor ads.

**Comment by yasasw** [comment]
@yasasw 
Check logs https://github.com/Duet3D/PluginRepository/actions/runs/3771926880

**Comment by yasasw** [comment]
API rate limit exceeded for 40.122.243.80. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details : 'https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting'
@yasasw Look into this
