### ISSUE TITLE
Updating plugin versions not working

### ISSUE THREAD

**Issue by MintyTrebor** [Duet3D/PluginRepository#619]
Submitted two updates for different plugins - both failed. Can you advise please.
It would appear that the version number is updating when opening the plugin's detail page in the pluginrepo, but the main pluginrepo page is not updating with the new version numbers.

**Comment by yasasw** [comment]
Hi @MintyTrebor 
Sorry about the delay in getting back.

I missed this.

I ran the update workflow for both your plugins and they worked this time. 

- https://github.com/Duet3D/PluginRepository/issues/630
- https://github.com/Duet3D/PluginRepository/issues/632

I will check the logs from previous runs and find out why they did not work.

Sorry about this again
Cheers
